//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.HostAdmin.UserControls {
    
    public partial class BlogsEditor {
        protected Subtext.Web.Admin.WebUI.MessagePanel messagePanel;
        protected Subtext.Web.Admin.WebUI.AdvancedPanel pnlResults;
        protected System.Web.UI.WebControls.CheckBox chkShowInactive;
        protected System.Web.UI.WebControls.Repeater rprBlogsList;
        protected System.Web.UI.HtmlControls.HtmlGenericControl lblNoMessages;
        protected Subtext.Web.Controls.PagingControl resultsPager;
        protected Subtext.Web.Admin.WebUI.AdvancedPanel pnlEdit;
        protected Subtext.Web.Controls.HelpToolTip blogEditorHelp;
        protected System.Web.UI.HtmlControls.HtmlImage Img3;
        protected Subtext.Web.Controls.HelpToolTip Helptooltip1;
        protected System.Web.UI.WebControls.TextBox txtTitle;
        protected Subtext.Web.Controls.HelpToolTip hostDomainHelpTip;
        protected System.Web.UI.WebControls.TextBox txtHost;
        protected System.Web.UI.HtmlControls.HtmlInputHidden virtualDirectory;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdAliasHost;
        protected System.Web.UI.WebControls.HiddenField hdnAliasId;
        protected System.Web.UI.WebControls.TextBox txtAliasHost;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdAliasList;
        protected System.Web.UI.WebControls.Repeater rprBlogAliasList;
        protected Subtext.Web.Controls.HelpToolTip applicationHelpTip;
        protected System.Web.UI.WebControls.TextBox txtApplication;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdAliasApplication;
        protected System.Web.UI.WebControls.TextBox txtAliasApplication;
        protected System.Web.UI.WebControls.DropDownList ddlGroups;
        protected System.Web.UI.HtmlControls.HtmlTableCell tbAliasActive;
        protected System.Web.UI.WebControls.CheckBox cbAliasActive;
        protected Subtext.Web.Controls.HelpToolTip helpUsername;
        protected System.Web.UI.WebControls.TextBox txtUsername;
        protected System.Web.UI.WebControls.Button btnAliasCancel;
        protected System.Web.UI.WebControls.Button btnAliasSave;
        protected System.Web.UI.HtmlControls.HtmlTableRow passwordRow;
        protected Subtext.Web.Controls.HelpToolTip helpPassword;
        protected System.Web.UI.WebControls.TextBox txtPassword;
        protected System.Web.UI.HtmlControls.HtmlTableRow passwordRowConfirm;
        protected System.Web.UI.WebControls.TextBox txtPasswordConfirm;
        protected System.Web.UI.WebControls.Button btnCancel;
        protected System.Web.UI.WebControls.Button btnSave;
    }
}
